version: "3"

volumes:
  mongodb_volume:

services:
  weather:
    build: .
    depends_on:
      - mymongo
    environment:
      - CITY=OMSK
  mymongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db