version: "3"

volumes:
  mongodb_volume:

services:
  weather:
    build: .
    environment:
      - MONGO_DB_ADDR=mymongo
      - MONGO_DB_PORT=27017
  mymongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db